controllers:
    resource: ../../src/Controller/
    type: annotation
user_controllers:
    resource: ../../src/Microservices/Identity/src/UI/UserController.php
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
